### ISSUE TITLE
Bad interaction between tags and a collection that follows

### ISSUE THREAD

**Issue by hbaragar** [Hobo/hobo#119]
I want the `<new-link>` for a child collection to precede the collection on the `<show-page>` of the parent.  However, this has the effect of creating two "empty" cards and suppressing the `<empty-message>` and `<else>` tags.

To recreate the problem:
* Create a new hobo application
* Create the parent and child resources:
```sh
    hobo g resource Parent name hm:children
    hobo g resource Child name bt:parent
    hobo g migrate
```
* Add a `children :children` directive to the parent model
* Add an `auto_actions_for :parent, [:new, :create]` directive to the child controller
* Add a `app/views/parents/show.dryml` file with the following contents:
```xml
    <show-page>
      <before-collection:>
         <a:children action="new" if="&can_create?(@parent.children)" param="new-link">
            <ht key="child.actions.new" count="1">
              New Child
            </ht>
         </a:children>
      </before-collection:>
    </show-page>
```
* `rails s`, create a parent record and see the two "empty" cards on the parent show page.

Note that using `<after-collection-heading:>` exhibits the same problem.  I don't know of any work-arounds.

I have found that the `action="new"` and `if="&can_create?(@parent.children)" param="new-link"` attributes each cause one of the "blank" cards to be created.

**Comment by iox** [comment]
I think this commit fixed this issue: https://github.com/Hobo/hobo/commit/bbc6e9b92ab42711e51f036a569acd5ef56da28d

I will close it for now. @hbaragar , feel free to reopen it if it's still happening!

Warm regards,
Ignacio
