### ISSUE TITLE
Dryml.precompile_taglibs is not working in latest Hobo

### ISSUE THREAD

**Issue by iox** [Hobo/hobo#13]
It looks like Dryml.precompile_taglibs has stopped working: https://groups.google.com/d/msg/hobousers/hihhVGA-3k4/1IMHUl0S4QAJ

**Comment by stevemadere** [comment]
This is a huge problem for me as I am deploying docker containers on Elastic Beanstalk and EB starts sending health check HTTP requests IMMEDIATELY after restarting my containers.  In fact, it sends two simultaneously which realizes a race condition and causes everything to get wedged.

I am using Puma multithreaded.  It appears that having two threads overlap their
first request causes this error to occur in all threads ever after:

```
I, [2016-08-16T04:49:55.597585 #23]  INFO -- : Completed 500 Internal Server Error in 69ms (ActiveRecord: 15.9ms)
F, [2016-08-16T04:49:55.598697 #23] FATAL -- :
ActionView::Template::Error (undefined method `render_page' for #<#<Class:0x0056227f0d19f0>:0x0056227f09e028>):

```

Additionally, it is clear that a bunch of stuff that gets compiled during precompile_taglibs
gets compiled AGAIN when the first request comes through.  I added log messages to mark
the events of starting and ending taglib precompilation and I see that between those
marks, several files are compiled that are then compiled again the first time a page request comes through that needs those files.
e.g.:

```
I, [2016-08-16T14:13:03.587094 #23]  INFO -- : done precompiling taglibs
I, [2016-08-16T14:14:39.274464 #23]  INFO -- : Started GET "/" for 65.36.82.193
at 2016-08-16 14:14:39 +0000
I, [2016-08-16T14:14:39.366533 #23]  INFO -- : Processing by FrontController#ind
ex as HTML
D, [2016-08-16T14:14:39.402958 #23] DEBUG -- :   ESC[1mESC[36mUser Load (2.9ms)
ESC[0m  ESC[1mSELECT  "users".* FROM "users" WHERE "users"."id" = $1 LIMIT 1ESC[
0m  [["id", 3755]]
I, [2016-08-16T14:14:39.451121 #23]  INFO -- :   DRYML: Compiled /usr/local/bund
le/bundler/gems/hobo-b9d103ed0426/dryml/taglibs/core.dryml in 0.02s
I, [2016-08-16T14:14:39.684502 #23]  INFO -- :   DRYML: Compiled app/views/tagli
bs/auto/rapid/cards.dryml in 0.10s
```

What could I change in precompile_taglibs or elsewhere in my configuration to make the taglib precompilation actually stick?

**Comment by stevemadere** [comment]
Well I finally managed to figure this out and we have two distinct problems here.
  1.  In Dryml::Railtie there is a call to app.config.to_prepare that completely wipes out
          the cache of precompiled taglibs IN ALL ENVIRONMENTS.  Therefore, calling
          Dryml.precomile_taglibs has no other effect than to waste some CPU time at startup.

  2.  Neither Dryml nor Dryml::Taglib are thread-safe because they each have a class
        variable called @cache which is manipulated without a Mutex guard.  As a result,
        one can be in the middle of compiling a Taglib or page template in one thread
        and a new request comes in in another thread and corruption mayhem ensues.

I'll submit a PR to fix both of these.
