### ISSUE TITLE
Firefox not clearing ajax forms (any more?)

### ISSUE THREAD

**Issue by haslinger** [Hobo/hobo#148]
I see Firefox (36.0.4) not clearing the text fields in Ajax-enabled Forms like this:

```html
<form with="&@message" update="mymessages">
  <input:content class="form-control" />
</form>
```

I also tried with ```autocomplete="off"```, but it's not a matter of autocomplete, it's just the last text, that's available/still there in Firefox.

**Update**: Running demo at http://demo.mercator.informatom.com/conversations/initiate
* Click Button "Konversation starten" once
* Textbox "Geben Sie hier Ihre Nachricht ein" on the next screen shows behaviour 

**Update of update**: Wait, I see the same behaviour on Chrome, also for the search field on Hobocentral. Is this desired behaviour and I just missed it up to now?

**Comment by iox** [comment]
Hi Stefan,

Congrats on the app, it looks great :). I think this is the desired behaviour. Could you try adding `reset-form` attribute to the form? (http://www.hobocentral.net/manual/ajax#reset-form)

If that doesn't work, you might use a "success" callback as a workaround (while we investigate what's broken).

Warm regards,
Ignacio

**Comment by haslinger** [comment]
That's totally it! I missed that in the documentation.
Thank you, I was already thinking about intercepting the submit, but this way it's way easier.
(And wait till it's ready ... 30 bugs to go and go to production ... it will be awesome ;-) )

**Comment by iox** [comment]
Great, looking forward to seeing it in production!
