### ISSUE TITLE
Status?

### ISSUE THREAD

**Issue by alanhorizon** [Hobo/hobo#173]
Is this a dead project? Lots of good concepts here, and specifically interested in the permissions system, but since this project is so monolithic and doesn't seem to be updated frequently, might be better off just using it as inspiration. Just asking to evaluate whether or not to look into Hobo more.

**Comment by iox** [comment]
Definitely not dead, though it's not updated as much as it could be.

The last version was released a couple of months ago, and we attempt to support the latest Rails/Ruby versions.

Collaborators are very welcome! Please feel free to talk in http://groups.google.com/group/hobousers

Regards,
Ignacio
