### ISSUE TITLE
Migration issue with latest Rails version

### ISSUE THREAD

**Issue by iox** [Hobo/hobo#186]
https://groups.google.com/forum/#!searchin/hobousers/Re$3A$20Rails$205.0.0.beta3$20-$20HoboFields$20has$20minor$20glitch/hobousers/sQS28cipGKQ/wVkTmqwoBQAJ

**Comment by owendall** [comment]
What do you think the LOE fpr this would be?

**Comment by iox** [comment]
This error has been fixed in master branch.
