### ISSUE TITLE
Conflict with Rails 4.0.6.rc1 - undefined method 'create_record' from hobo_support/fixes/module.rb:14

### ISSUE THREAD

**Issue by voobofdoom** [Hobo/hobo#90]
tried with jruby-1.7.12, ruby-2.0.0, ruby-2.1.2, ruby-1.9.3
$ rvm use [ruby_version]
$ rvm gemset create hobotry
$ rvm use [ruby_version]@hobotry
$ gem install hobo
$ hobo new testapp
expected output goes by.....
and then this:
[ruby_version]@hobotest/gems/hobo_support-2.1.0/lib/hobo_support/fixes/module.rb:14:in `alias_method': undefined method`create_record' for class `ActiveRecord::Associations::HasManyThroughAssociation' (NameError)

trying to run rake -T will generate the same error.

please let me know if i can provide any other details.
generally though, i grabbed a fresh ruby/gemset, installed hobo gem, tried to create a new app and failed with the above error, i reproduced it on 2 machines(debian 7, ubuntu 12.04).

Being a complete newcomer to hobo, i am not yet aquainted with the codebase and the way things are done, so i don't really understand the purpose of alias_method_chain...

**Comment by haslinger** [comment]
Huh, I guess I have to open this one up again, it (the original error mentioned in the subject) also happens with 4.0.13 installed before... 

```
stefan@mars:/var/rails$ hobo new hobo-demo
...
generate    hobo:setup_wizard
/home/stefan/.rvm/gems/ruby-2.1.5/gems/hobo_support-2.1.0/lib/hobo_support/fixes/module.rb:14:in `alias_method': undefined method `create_record' for class `ActiveRecord::Associations::HasManyThroughAssociation' (NameError)
...
stefan@mars:/var/rails$ rails -v
Rails 4.0.13
```

I'll try the workarounds mentioned...

**Comment by haslinger** [comment]
Ok, on my side the trouble maker was
```
gem "hobo", "= 2.1.0"
```
but exchanging it for 
```
```
solved the issue, so no need to reopen the issue.
