### ISSUE TITLE
Hobo 2.2 incompatible w/ Rails 4.1.1

### ISSUE THREAD

**Issue by WhiteFire-Sondergaard** [Hobo/hobo#97]
While attempting to create an app

```
wfire@sneppy:~/SL$ hobo new TestApp
Hobo Command Line Interface 2.1.1
Generating Rails infrastructure...
...
       apply  /tmp/hobo_app_template
     gemfile    hobo (= 2.1.1)
     gemfile    protected_attributes
The template [/tmp/hobo_app_template] could not be loaded. Error: Unable to activate rails-4.0.8, because activesupport-4.1.1 conflicts with activesupport (= 4.0.8), actionpack-4.1.1 conflicts with actionpack (= 4.0.8), railties-4.1.1 conflicts with railties (= 4.0.8)
```

I realize that hobo is not rails 4.1.1 compatible, but the problem is, it's trying to load 4.1.1 parts if they are installed (say, for another rails application.)

This makes it impossible to build a hobo app at all.

**Comment by iox** [comment]
Now we are compatible with Rails 4.2! I think this is solved for now, please write if you encounter issues.
